import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Clock3 } from "lucide-react";
import { notFound } from "next/navigation";
import { FadeIn } from "@/components/ui/fade-in";
import { roadmapPages, site } from "@/lib/content";

type Role = keyof typeof roadmapPages;
export function generateStaticParams() { return Object.keys(roadmapPages).map((role) => ({ role })); }
export async function generateMetadata({ params }: { params: Promise<{ role: string }> }): Promise<Metadata> { const { role } = await params; const data = roadmapPages[role as Role]; return data ? { title: data.title, description: data.description, alternates: { canonical: `/roadmaps/${role}` } } : {}; }

export default async function RoadmapRolePage({ params }: { params: Promise<{ role: string }> }) {
  const { role } = await params; const data = roadmapPages[role as Role]; if (!data) notFound();
  const jsonLd = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Roadmaps", item: `${site.url}/roadmaps` }, { "@type": "ListItem", position: 2, name: data.title, item: `${site.url}/roadmaps/${role}` }] };
  return <main><section className="section pb-20 md:pb-28"><div className="shell"><Link href="/roadmaps" className="inline-flex items-center gap-2 text-[13px] text-muted hover:text-ink"><ArrowLeft size={15} /> All roadmaps</Link><FadeIn className="mt-14 max-w-[820px]"><p className="eyebrow">{data.shortTitle} / roadmap preview</p><h1 className="headline mt-6">{data.title}</h1><p className="body-copy mt-6 max-w-[640px] text-[18px]">{data.intro}</p><div className="mt-8 inline-flex items-center gap-2 rounded-full border border-line px-3 py-2 text-[12px] text-muted"><Clock3 size={14} /> Typical focused cycle · {data.weeks}</div></FadeIn></div></section><section className="border-t border-line"><div className="shell grid gap-12 py-20 md:grid-cols-[.8fr_1.2fr] md:py-28"><div><p className="eyebrow">The order</p><h2 className="mt-5 text-[30px] font-semibold leading-tight tracking-[-0.04em]">Build the signal in layers.</h2><p className="mt-5 max-w-[310px] text-[15px] leading-6 text-muted">Each stage is a useful checkpoint, not a gate. Pathloom will later turn these into nodes that update with your activity.</p></div><div className="divide-y divide-line border-y border-line">{data.skills.map(([number, title, copy]) => <div key={number} className="grid grid-cols-[40px_1fr] gap-4 py-6"><span className="pt-1 text-[12px] text-accent">{number}</span><div><h3 className="text-[18px] font-semibold tracking-[-0.025em]">{title}</h3><p className="mt-2 text-[14px] leading-6 text-muted">{copy}</p></div></div>)}</div></div></section><section className="section"><div className="shell grid gap-12 md:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Free starting points</p><h2 className="mt-5 text-[30px] font-semibold leading-tight tracking-[-0.04em]">Use resources that leave you with proof.</h2></div><div className="grid gap-3 sm:grid-cols-2">{data.resources.map((resource) => <div key={resource} className="rounded-card border border-line p-5 text-[14px] font-medium">{resource}<p className="mt-3 text-[12px] font-normal leading-5 text-muted">A focused resource is better than five open tabs.</p></div>)}</div></div></section><section className="section pt-0"><div className="shell"><div className="rounded-shell border border-line bg-muted-surface p-8 md:flex md:items-center md:justify-between md:p-12"><div><p className="eyebrow">Make it personal</p><h2 className="mt-4 text-[30px] font-semibold tracking-[-0.04em]">This gets useful when it reflects your work.</h2></div><Link href="/onboarding" className="button-primary mt-7 md:mt-0">Map this path <ArrowRight size={16} /></Link></div></div></section><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /></main>;
}
