import Link from "next/link";
import { ArrowRight, Check, LockKeyhole } from "lucide-react";
import { goalById, nodesForGoal } from "@/lib/phase2-data";
import type { PublicProfilePayload } from "@/lib/public-profile";

export function PublicProfileCard({ profile }: { profile: PublicProfilePayload }) {
  const goal = goalById(profile.goalId); const nodes = nodesForGoal(profile.goalId); const completed = new Set(profile.completedNodeIds); const percent = Math.round((profile.completedNodeIds.length / nodes.length) * 100);
  return <main className="section pt-20"><div className="shell"><div className="mx-auto max-w-[760px]"><div className="flex flex-col gap-8 border-b border-line pb-10 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Public path</p><h1 className="mt-4 text-[clamp(42px,7vw,72px)] font-semibold leading-[.98] tracking-[-.06em]">{profile.displayName || `@${profile.username}`}</h1><p className="mt-4 text-[15px] text-muted">A progress path shared intentionally on Pathloom.</p></div><div className="flex h-28 w-28 shrink-0 flex-col items-center justify-center rounded-full border-[8px] border-accent border-r-line"><span className="text-[25px] font-semibold tracking-[-.05em]">{percent}%</span><span className="text-[10px] uppercase tracking-[.08em] text-muted">visible</span></div></div><section className="mt-8 rounded-shell border border-line bg-surface p-6 shadow-[var(--shadow-soft)] md:p-8"><p className="eyebrow">Working toward</p><h2 className="mt-3 text-[28px] font-semibold tracking-[-.04em]">{goal.title}</h2><p className="mt-3 max-w-[620px] text-[14px] leading-6 text-muted">{goal.description}</p>{profile.deadline && <p className="mt-5 text-[12px] font-medium text-accent">Target date · {new Intl.DateTimeFormat("en", { month: "long", day: "numeric", year: "numeric" }).format(new Date(`${profile.deadline}T12:00:00`))}</p>}<div className="mt-8 grid gap-3 sm:grid-cols-2">{nodes.map((node) => <div key={node.id} className={`rounded-card border p-4 ${completed.has(node.id) ? "border-accent/30 bg-accent-soft" : "border-line bg-muted-surface"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.1em] text-muted">{node.eyebrow}</p><p className="mt-2 text-[14px] font-semibold">{node.title}</p></div>{completed.has(node.id) ? <Check size={16} className="mt-0.5 shrink-0 text-accent" /> : <LockKeyhole size={15} className="mt-0.5 shrink-0 text-quiet" />}</div><p className="mt-2 text-[12px] leading-5 text-muted">{completed.has(node.id) ? "Marked complete in this shared snapshot." : "Still part of the path ahead."}</p></div>)}</div></section><div className="mt-8 flex flex-col gap-4 rounded-card border border-line px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-[12px] leading-5 text-muted">This is an intentional snapshot, not a live view of private account data.</p><Link href="/onboarding" className="group inline-flex items-center gap-2 text-[12px] font-semibold text-accent">Build your own path <ArrowRight size={14} className="transition-transform group-hover:translate-x-1" /></Link></div></div></div></main>;
}
