"use client";

import { AlertTriangle, CheckCircle2, CloudDownload, RefreshCw, WifiOff } from "lucide-react";
import { usePhase2 } from "@/components/app/phase2-provider";

const labels = { github: "GitHub", leetcode: "LeetCode", codeforces: "Codeforces" } as const;
export function SyncPanel() {
  const { state, syncing, syncProviders } = usePhase2();
  const hasAccounts = Object.values(state.accounts).some(Boolean);
  const syncLabel = state.sync.status === "never" ? "Never synced" : state.sync.status === "success" ? "Synced successfully" : state.sync.status === "partial" ? "Synced with notes" : state.sync.status === "error" ? "Sync needs attention" : "Syncing";
  return <section className="rounded-shell border border-line bg-surface p-6 md:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="eyebrow">Activity sync</p><h2 className="mt-3 text-[22px] font-semibold tracking-[-.035em]">Let your work count.</h2><p className="mt-2 max-w-[540px] text-[13px] leading-5 text-muted">Pathloom reads only public activity and turns it into evidence. Manual completions are never removed when a provider is unavailable.</p></div><button type="button" onClick={() => void syncProviders()} disabled={syncing || !hasAccounts} aria-busy={syncing} className="button-primary shrink-0 disabled:cursor-not-allowed disabled:opacity-45"><RefreshCw aria-hidden="true" size={15} className={syncing ? "animate-spin" : ""} />{syncing ? "Syncing" : "Sync now"}</button></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{(Object.entries(state.accounts) as Array<[keyof typeof labels, string]>).map(([provider, handle]) => { const snapshot = state.sync.snapshots.find((item) => item.provider === provider); return <div key={provider} className="rounded-card border border-line bg-muted-surface p-4"><div className="flex items-center justify-between"><span className="text-[12px] font-semibold">{labels[provider]}</span>{snapshot && snapshot.warnings.length === 0 ? <CheckCircle2 aria-hidden="true" size={15} className="text-accent" /> : handle ? <AlertTriangle aria-hidden="true" size={15} className="text-amber-500" /> : <WifiOff aria-hidden="true" size={15} className="text-quiet" />}</div><p className="mt-2 truncate text-[12px] text-muted">{handle ? `@${handle}` : "Not connected"}</p><p className="mt-3 text-[11px] text-quiet">{snapshot ? `${snapshot.activity.events30d} recent events` : "Waiting for a handle"}</p></div>; })}</div><div aria-live="polite" className="mt-5 flex flex-col gap-2 border-t border-line pt-4 text-[12px] text-muted sm:flex-row sm:items-center sm:justify-between"><span className="inline-flex items-center gap-2"><CloudDownload aria-hidden="true" size={14} className="text-accent" />{syncLabel}{state.sync.lastSyncedAt ? ` · ${new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(state.sync.lastSyncedAt))}` : ""}</span><span>{state.sync.evidence.filter((item) => item.qualifies).length} rules currently qualify</span></div>{state.sync.warnings.length > 0 && <div role="alert" className="mt-4 rounded-card border border-amber-200 bg-amber-50 p-3 text-[12px] leading-5 text-amber-900">{state.sync.warnings.join(" ")}</div>}</section>;
}
