import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Mail } from "lucide-react";
import { notFound } from "next/navigation";
import { FadeIn } from "@/components/ui/fade-in";
import { legalContent, site } from "@/lib/content";

const pages: Record<string, { title: string; description: string; eyebrow: string; intro: string; blocks: Array<{ heading: string; body: string }> }> = {
  "how-it-works": { title: "How Pathloom works", description: "See how Pathloom turns a career goal into a living skill tree and a weekly plan.", eyebrow: "The product loop", intro: "Your career plan should reflect the work you actually do. Pathloom makes that visible.", blocks: [{ heading: "Start with a role and a date", body: "Choose a SWE or APM/PM goal, add a deadline, and get a map of the skills and evidence that role asks for." }, { heading: "Let progress come from real activity", body: "GitHub, Codeforces, and LeetCode can contribute public signals. Things that cannot be tracked—mock interviews, applications, shipped projects—stay easy to mark manually." }, { heading: "Re-plan every week", body: "The tree is not a poster. It notices gaps, looks at your recent pace, and gives you a short next plan. If life gets busy, the plan adjusts instead of making you feel behind." }, { heading: "Share only what you choose", body: "Your profile is private by default. When you opt in, a clean progress card gives friends, mentors, or peers a useful view of where you are." }] },
  "about": { title: "About Pathloom", description: "Why Pathloom exists and who it is for.", eyebrow: "A small idea with a long horizon", intro: "Pathloom is for the student who has ten tabs open and still is not sure what to do tonight.", blocks: [{ heading: "Made for the work between intention and outcome", body: "Career preparation is often fragmented across problem lists, repositories, notes, spreadsheets, and application trackers. Pathloom brings the signal together without pretending the path is linear." }, { heading: "Designed for students in India, useful everywhere", body: "The first version is shaped around Indian B.Tech and BCA students navigating internships and placements, while staying useful for self-taught developers and career switchers around the world." }, { heading: "Quiet by design", body: "No noisy streak theatrics or vague AI advice. Just a calm map, honest progress, and a clear next step." }] },
  "contact": { title: "Contact Pathloom", description: "Ask a question, share feedback, or report a problem with Pathloom.", eyebrow: "Say hello", intro: "Pathloom is being built in the open, one useful detail at a time.", blocks: [{ heading: "Email is the simplest route", body: "For feedback, accessibility issues, data requests, or partnership ideas, send a note to the placeholder contact below. Replace it before launch." }] },
  "changelog": { title: "Changelog", description: "A short record of what is changing in Pathloom.", eyebrow: "Small steps, written down", intro: "Pathloom is early. This is where the product keeps its promises visible.", blocks: [{ heading: "October 2026 · The first thread", body: "The Pathloom public shell, skill-tree preview, career roadmap content, theme system, legal templates, and consent controls are now in place." }, { heading: "Next · Make the tree real", body: "The next phase adds sign-in, goal selection, a real skill-tree canvas, manual progress, and the first saved dashboard." }] },
  "faq": { title: "Frequently asked questions", description: "Answers about Pathloom, progress tracking, integrations, and privacy.", eyebrow: "Questions, answered plainly", intro: "If the answer is not here, ask us. The product is still learning too.", blocks: [{ heading: "Is Pathloom a static roadmap?", body: "No. Roadmap pages are useful starting points, but the product is built around live tracking, weekly replanning, and a shareable progress card." }, { heading: "Do I need to connect every account?", body: "No. You can use manual nodes for work that cannot be tracked. Connections are optional and should only use public activity or an authorised OAuth session." }, { heading: "Is my profile public?", body: "No. Profiles are private by default. A profile becomes shareable only after you explicitly turn visibility on." }, { heading: "Does Pathloom guarantee an internship?", body: "No. Progress and plans are informational. They can help you prepare with more focus, but no tool can guarantee a job or interview." }, { heading: "What happens if an integration breaks?", body: "The app should fail gracefully and let you mark the work manually. Your preparation should not stop because a third-party endpoint changed." }] }
};

export function generateStaticParams() { return [...Object.keys(pages), ...Object.keys(legalContent)].map((slug) => ({ slug })); }

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const data = pages[slug] || legalContent[slug];
  if (!data) return {};
  return { title: data.title, description: data.description, alternates: { canonical: `/${slug}` }, openGraph: { title: data.title, description: data.description, url: `${site.url}/${slug}` }, twitter: { card: "summary_large_image", title: data.title, description: data.description } };
}

export default async function PublicPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const legal = legalContent[slug];
  const data = pages[slug];
  if (!data && !legal) notFound();
  if (legal) return <main className="section"><div className="shell max-w-[780px]"><FadeIn><p className="eyebrow">Pathloom / legal</p><h1 className="headline mt-6">{legal.title}</h1><p className="body-copy mt-6 max-w-[640px]">{legal.description}</p><div className="prose-page mt-12 border-t border-line pt-2">{legal.sections.map((section) => <section key={section.heading}><h2>{section.heading}</h2>{section.body.map((paragraph) => <p key={paragraph} className="mt-3">{paragraph}</p>)}</section>)}</div></FadeIn></div></main>;
  const jsonLd = slug === "faq" ? { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: data.blocks.map((block) => ({ "@type": "Question", name: block.heading, acceptedAnswer: { "@type": "Answer", text: block.body } })) } : undefined;
  return <main><section className="section pb-20 md:pb-28"><div className="shell max-w-[900px]"><FadeIn><p className="eyebrow">{data.eyebrow}</p><h1 className="headline mt-6 max-w-[760px]">{data.title}</h1><p className="body-copy mt-6 max-w-[620px] text-[18px]">{data.intro}</p>{slug === "contact" && <a href="mailto:{{CONTACT_EMAIL}}" className="button-primary mt-8">Email {"{{CONTACT_EMAIL}}"} <Mail size={15} /></a>}</FadeIn></div></section><section className="border-t border-line"><div className="shell divide-y divide-line">{data.blocks.map((block, index) => <FadeIn key={block.heading} delay={index * 0.04}><article className="grid gap-5 py-12 md:grid-cols-[.8fr_1.2fr] md:gap-16 md:py-16"><h2 className="text-[22px] font-semibold tracking-[-0.035em]">{block.heading}</h2><p className="max-w-[560px] text-[16px] leading-7 text-muted">{block.body}</p></article></FadeIn>)}</div></section><section className="section pt-20"><div className="shell"><Link href="/onboarding" className="group inline-flex items-center gap-2 text-sm font-semibold text-accent">See your path <ArrowRight size={16} className="transition-transform group-hover:translate-x-1" /></Link></div></section>{jsonLd && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />}</main>;
}
